package com.deiva.deiva;

import an.awesome.pipelinr.Pipeline;
import com.deiva.deiva.infraestructure.AddUser;
import com.deiva.deiva.infraestructure.Users;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.deiva.deiva.model.entities.User;

import javax.validation.Valid;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    // @Autowired
    private final Pipeline pipeline;
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    @Autowired
    public MainController(Pipeline pipeline) {
        this.pipeline = pipeline;
    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody User addNewUser (@Valid @RequestBody User user) {
        return new AddUser(user).execute(pipeline);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return new Users().execute(pipeline);
    }
}